version: '3.7'
services:
  opensearch:
    image: opensearchproject/opensearch:2.2.0
    environment:
      discovery.type: single-node
      plugins.segurity.disable: true
      compatibility.override_main_response_version: true
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.2.0
    ports:
      - 5601:5601
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]' # must be a string with no spaces when specified as an environment variable
      DISABLE_SECURITY_DASHBOARD_PLUGIN: "true"
